### ISSUE TITLE
Deactivate or unlink a paired/connected device manually

### ISSUE THREAD

**Issue by trulow** [crysxd/OctoApp-Plugin#12]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A way to deactivate or unlink a paired/connected device manually

**Describe alternatives you've considered**
N/A

**Additional context**
It would be useful to unpair or unlink a previously paired/connected device via the plugin manually for those times where the device is no longer available to uninstall the app.

**Comment by crysxd** [comment]
Thanks for the ticket!

I don't think this is necessary at the moment. From your statement I understand that you e.g. factory reset the device or even lost it? 

Basically how the devices are managed is that Google (which delivers the notifications) will let the OctoApp plugin know if an app installation is no longer available. This happens the next time a notification is sent if you uninstall the app or after 30 days in case the phone no longer checks in with Google's server. I think I also have some code to kick app installations out after 2 weeks if they don't check in with the plugin.

There is also no downside for you in having a non-existent device connected to the plugin (until it get's removed automatically). E.g. the number of network requests the plugin makes is constant and not linked to the number of devices connected.

I'd close this for know, let me know if you see a reason for manually removing the device! I will also update the description in the plugin to make this process more transparent :)
