### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by junkheadog** [crysxd/OctoApp-Plugin#15]
im having a problem with octoapp for my android its saying that the versions on the app and on octoprint are mismatched causing the connection to get refused

**Comment by crysxd** [comment]
Please post a screenshot of the error, I'm not familiar with this error. 

Generally, I can't offer support for the app here, please send your request to hello@octoapp.eu or better use the bug report feature of the app (main menu > Settings > FAQ & Help > Report a bug) or keep the "Need help?" test during login pressed for 2 seconds.
