### ISSUE TITLE
Obico support? 

### ISSUE THREAD

**Issue by 343GuiltySpark-04** [crysxd/OctoApp-Plugin#18]
Does the spaghetti detective plugin still work now that its depreciated and is now Obico? if not are there plans to add support for this new (albeit uneeded version)?

**Comment by 343GuiltySpark-04** [comment]
it looks like Obico is its own payed thing which if so is sad since i liked having a reverse proxy for my octoprint 

Edit: it does seem to have a client API so that's good news

**Comment by crysxd** [comment]
I do not know what you are referring to, the Obico plugin is supported since it was launched and replaced the TSD integration.
