### ISSUE TITLE
OctoKlipper Assisted Bed Leveling support

### ISSUE THREAD

**Issue by CobraA1** [crysxd/OctoApp-Plugin#19]
**Is your feature request related to a problem? Please describe.**
My printer is not next to my computer, so Klipper's assisted bed leveling is difficult to use. I have to pull out my cell phone, and OctoPrint's web UI is not cell phone friendly.

**Describe the solution you'd like**
I would like to be able to use Klipper's built-in assisted bed leveling feature from OctoApp.

**Describe alternatives you've considered**
The only alternative is to use the web UI of OctoPrint, but that is not ideal for cell phones.

**Additional context**
I'm sure there are many other features that could be added from OctoPrint/Klipper (such as access to Klipper's macros), but this is the most pressing issue I've found, and would be a huge quality of life improvement if implemented.

**Comment by crysxd** [comment]
Thanks for the issue! I do not keep feature requests here as this is only the plugin, not the app. I linked this ticket in the [main issue ](https://gitlab.com/realoctoapp/octoapp/-/issues/2101) and will close it :) I also plan on building [something similar](https://gitlab.com/realoctoapp/octoapp/-/issues/7) directly into OctoApp at some point.
