### ISSUE TITLE
Android application bottom bar is hidden under device navigation bar

### ISSUE THREAD

**Issue by CoryCharlton** [crysxd/OctoApp-Plugin#23]
I would follow the instructions and report this but from inside the app but since the bottom navigation bar is hidden under the system navigation bar I cannot access that menu.

![Screenshot_20230315-203058_OctoApp.jpg](https://user-images.githubusercontent.com/10094287/225507045-b2274025-be39-40c5-99ea-43e22141fe53.jpg)

I'm running the latest version of OctoApp

**Comment by crysxd** [comment]
That looks really odd! Could you send me an email to hello@octoapp.eu? That will create a ticket in my normal ticketing system.

Could you tell me what device and Android version you are using?

**Comment by CoryCharlton** [comment]
I sent more details as requested.
