### ISSUE TITLE
WARNING - Failed to get webcam, snapshot Invalid URL

### ISSUE THREAD

**Issue by gursel58** [crysxd/OctoApp-Plugin#24]
About every five seconds I get the following message in my ocoprint.log file:

octoprint.plugins.octoapp - WARNING - Failed to get webcam snapshot Invalid URL '': No scheme supplied. Perhaps you meant http://?

I have checked in the octoapp and cant find any settings
I checked Webcam and Timelapse and everything is working correctly

What did I miss 

Thanks

**Comment by crysxd** [comment]
Firstly, it's just a warning and you can generally ignore it. I already have a plugin update ready that removes the warning log. This might impact features like the data saver webcam and webcam widgets, but nothing major will break.

The issue should be that your snapshot URL is empty, you can change it in OctoPrint's webcam settings.
