### ISSUE TITLE
Webcam URL calculation in app

### ISSUE THREAD

**Issue by gjedeer** [crysxd/OctoApp-Plugin#29]
I have Octoprint exposed behind nginx like https://domain/octoprint/. This worked great with Octoapp except for the webcam. It seems to have a hard coded webcam URL to https://domain/webcam/?action=stream - ignoring the path part of the URL.

Would it be possible to add the path part to the generated URL (or if for some reason it's impossible, add a separate setting to webcam URL?)

**Comment by crysxd** [comment]
Please report a bug via the apps FAQ and help menu so I can see the app logs and what the app is doing. What you describe should work.

Thanks!

**Comment by crysxd** [comment]
Just a hunch, if your path starts with a `/` the app will behave like you describe. Make sure it's actually a relative path, e.g. `webcam/?action=stream` and not `/webcam/?action=stream`

**Comment by gjedeer** [comment]
That helped, thanks!

If someone else comes across this problem: it looks like OctoApp is reading the Octoprint value from Settings->Webcam, where you set the URL yourself. That's what @crysxd is talking about. The relative path does not work but the absolute URL does. There's no setting in OctoApp itself.

**Comment by crysxd** [comment]
Thanks for the update! Yes, you are correct where the path is coming from. Just to clarify, with the base URL `https://domain/octoprint/` as in your example, the absolute path `/octoprint/webcam?action=stream` should be equivalent to `webcam?action=stream`. The absolute path is appended to the host only (`https://domain` + `/octoprint/webcam?action=stream`) and the relative path on the full base URL (`https://domain/octoprint/` + `webcam?action=stream`). The leading `/` is what makes the difference in absolute to relative path.

If that's not the case, please let me know, I need to double check this then
