### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by K4CZP3R** [crysxd/OctoApp-Plugin#3]
**Is your feature request related to a problem? Please describe.**
I can't experience this app on iOS-based device.

**Describe the solution you'd like**
Make iOS version of the app.

**Describe alternatives you've considered**
For now, I'm using the web-interface of OctoPrint.

**Additional context**
No additional context.

**Comment by crysxd** [comment]
Hi! I'm not planning on releasing a iOS version soon. The problem is purely my limited time and the Android app already keeps me plenty busy. I'd be happy to offer a iOS version some day though :)
