### ISSUE TITLE
Something ... I don't know how to solve

### ISSUE THREAD

**Issue by Martin-Ox** [crysxd/OctoApp-Plugin#34]
I don't know if it's a bug or what ....  But it's a strange behaviour from Octoapp or Octoprint of combination with ?????  ....
When printing round objects I came across some zits and blobs on the outeside of the print.
I noticed the printerhead stopt moving ... and then continues, leaving some material on the print.
Strange....why does it stop moving ?

Disabled al plugins and ... nothing. No stops, no zits no blobs no stops of the printerhead ... nothing at all.
One by one enabled the plugins. No issues....until enabeling the Octoapp plugin.

Hmmm. Why ?

Had an old Thin Client, installed Debian on it and installed Octoprint and the same plugins as on the other one (Rpi4 8Gb)
Including an enabled OctoApp plugin.

Guess what ? No zits, blobs, printer pauses ................................................

Because of the fact that a Thin Client is using more power then a RPi, I do like to go back to the RPi.
When on holiday the last couple of weeks, there was a new version of Octoprint  release.
Installed that one, (clean install) and installed the plugins I am using. Including the OctoApp plugin.
And there it is again... pausing printerhead movements :-( :-(

Rpi 4 with 8Gb and 32Gb SDCard

HP 610T Thin Client with 8Gb and 16Gb SSD 

I don't get it anymore, maybe you or someone from the community knows a solution.

**Comment by crysxd** [comment]
Can you send a bug report from the app via main menu > Settings > Report a bug? Then I get a overview on what your setup is and also get the plugin logs. We can continue in the support ticket, I will close this for now :) 

I have a suspicion what's going on....
