### ISSUE TITLE
Notifications for when printer needs user interaction

### ISSUE THREAD

**Issue by m3rlin87** [crysxd/OctoApp-Plugin#36]
**Is your feature request related to a problem? Please describe.**
In the event the printer needs user interaction from say a crash, run out of filiment, filiment change it triggers an input requirement for a user to directly interact with the printer. 

**Describe the solution you'd like**
Would like to get an push notification when that situation happens

**Describe alternatives you've considered**
I have looked through the Octoapp and not seeing that this notification is currently available, unless I am blind :)

Currently getting this notification via email from Octoeverywhere but would like something additional similar to the finish print notification from Octoapp :)

**Additional context**

**Comment by crysxd** [comment]
This is already available if you have the OctoApp plugin installed. There are notifications for filament runout, print paused / filament change and printer beep. If you think this doesn't work for you please report a bug via the app's FAQ and help section.

**Comment by m3rlin87** [comment]
Ok ill take a look at the notifications again in the app, as I do have the plugin installed. But only get the push notifications for finished print. Thanks
