### ISSUE TITLE
Pinch to zoom camera view on iOS

### ISSUE THREAD

**Issue by emelbardis** [crysxd/OctoApp-Plugin#38]
**Is your feature request related to a problem? Please describe.**
I've just moved from Octopod to Octoapp and lifetime subscribed. You work is amazing and the app is great to use. The only thing I miss is the ability to pinch zoom in to investigate the nozzle or quality of print from remote.

**Describe the solution you'd like**
I'd like to be able to zoom in on my web cam view from both portrait and landscape

**Comment by crysxd** [comment]
It's on the list but I didn't get it to work in a satisfactory way yet. 
The ticket is here: https://gitlab.com/realoctoapp/octoapp/-/issues/2333
