### ISSUE TITLE
Add configurable alarms for OctoApp Wear OS

### ISSUE THREAD

**Issue by puterboy** [crysxd/OctoApp-Plugin#43]
Would be great to have configurable alarms to alert you of common and/or critical printer events.
I find that typical emails or sms get lost in the noise.

It would be great to have a configurable alarm (including choice of ringtone) for:
- Print completed
- Print error
- Filament change
- Pause
-etc.

**Comment by crysxd** [comment]
This should be configurable via the system settings. All different types of notifications in OctoApp are separated in different categories. While they are not customizable all "pause" notifications (including filament change etc) have a dedicated notification sound and the print done notification also has a unique sound
