### ISSUE TITLE
Knock the Pants Off TSD

### ISSUE THREAD

**Issue by escfoe2** [crysxd/OctoApp-Plugin#5]
One of the biggest features I enjoy about TSD is that it captures a Timelapse for every print.  You already capture the stream from the camera.  Capture a frame every 5-10 seconds or so, compile it to whatever video format makes the most sense, and save it to the Pi.  It can be a setting in the plugin to enable whether we want to capture Timelapses or not.  The rate at which frames are captured can be a setting too.  A default value of 5 or 10 makes sense.

Let us access them from the app as well as octoprint.  I'd be so impressed with that and I think your solution would immediately be the top solution over TSD.  Over everything, honestly.

**Comment by crysxd** [comment]
Timelapse support is planned already. I hoped to add it to the December release, but other stuff got priority. The Timelapse will be driven by OctoPrint's Timelapse though, so no changes to this plugin needed! Thanks for the suggestion!
