### ISSUE TITLE
Add Support for "Time to Pause"

### ISSUE THREAD

**Issue by s00se** [crysxd/OctoApp-Plugin#50]
**Is your feature request related to a problem? Please describe.**
Users who have to manually intervene during a pause (to insert an object), an option to see "Time to Pause" would be good. There is currently an existing OctoPrint plugin called [TimeToFilament](https://github.com/eyal0/OctoPrint-TimeToFilament) which will pre-process for any regex and display it. 

**Describe the solution you'd like**
Add a "Time to Pause" on the Print dashboard, where "Spent, Left, and ETA" are displayed.

**Describe alternatives you've considered**
An option to include this in the persistent notification on Android would also be great added usability.

**Comment by crysxd** [comment]
I copied the ticket to GitLab, closing here
https://gitlab.com/realoctoapp/octoapp/-/issues/2486

If more people request it I will consider adding support, but this does basically solve the same problem as this ticket: https://gitlab.com/realoctoapp/octoapp/-/issues/1382
