### ISSUE TITLE
Add Support for UPS Status

### ISSUE THREAD

**Issue by s00se** [crysxd/OctoApp-Plugin#51]
**Is your feature request related to a problem? Please describe.**
The ability to see a connected UPS would be good. There is an existing plugin for OctoPrint, [UPS](https://plugins.octoprint.org/plugins/ups/) which provides this to the main UI, being able to see this on the OctoApp dashboard would be great for users who have a UPS attached to their print systems and deal with power outages.

**Describe the solution you'd like**
If plugin is installed, add UPS status to Print dashboard of OctoApp, showing the 3 supplied values of Status, Charge, and Runtime.

**Comment by crysxd** [comment]
Thanks for your feature request! 
I was looking into the plugin but I don't think the install base is large enough to warrant supporting it in OctoApp. Supporting a plugin always comes with a lot of effort on my end, not only for the initial implementation but also in testing the integration and making sure it keeps working over time and supporting people if the integration doesn't work as expected. For this reason I'm a bit more selective by now which plugin I add support for.
