### ISSUE TITLE
KIAUH Integration

### ISSUE THREAD

**Issue by bertenvdb** [crysxd/OctoApp-Plugin#61]
Intergration in the popular Klipper tool [KIAUH ](https://github.com/dw-0/kiauh)(Klipper Installation And Update Helper) would be beneficial to Klipper users and the developer of OctoApp. 
For the Klipper users it would be an even easier way to install and maintain the OctoApp Plugin.
For the developer of OctoApp this means an additional channel for discovery of OctoApp.

The OctoApp Plugin installer says it's based on the OctoEverywhere Plugin, which is [available ](https://github.com/dw-0/kiauh/blob/master/scripts/octoeverywhere.sh)in KIAUH, so integration seems pretty straightforward. 

I'd happily do it myself if I had the time, but life's a bit hectic at the moment.

**Comment by crysxd** [comment]
Of course planned :) Just didn't find time yet to do so. Closing in favor of ticket in the main project.

https://gitlab.com/realoctoapp/octoapp/-/issues/2449
