### ISSUE TITLE
Install error on fresh Octoprint installation

### ISSUE THREAD

**Issue by doza62** [crysxd/OctoApp-Plugin#62]
I think related to #13 and #39.

After installing I get first notice of something going wrong:
![image](https://github.com/crysxd/OctoApp-Plugin/assets/14064394/032b2d2f-ced4-4f10-8faf-87ab42b083f4)

Checking octoprint.log:
```
2024-03-23 20:36:21,347 - octoprint.plugin.core - ERROR - Error loading plugin octoapp
  File "/home/rodri/octoprint/env/lib/python3.7/site-packages/octoprint_octoapp/__init__.py", line 29, in <module>
  File "/home/rodri/octoprint/env/lib/python3.7/site-packages/octoprint_octoapp/webcamsnapshots.py", line 6, in <module>
```

Trying to manually load dependencies I've found PIL was throwing an error:
![image](https://github.com/crysxd/OctoApp-Plugin/assets/14064394/fd9103d0-147e-4baa-9558-a091f161691f)

After a quick google I did the following install:
`sudo apt-get install libopenjp2-7`

Restarted octoprint and voila! it works now. I'm guessing a dependency check is missing. I've noticed multiple plugins rely on that library. I don't know if it is posible to install it automatically if missing or throw an error.

Anyhow, great plugin! I'm trying it out now to its full extent. I've only noticed a missing feature that would be great: notification when preheat is done. I like to preheat first, then get to my machine before starting to print. But I always remember I left it heating up after an hour or so :/

**Comment by crysxd** [comment]
Thanks for reporting, but I don't think there is much I can do on my end. I can only specify the packages I need, if they fail to install there is something wrong with the underlying system (in your case the missing lib)

I will close this as there is no action needed, but other can find it! Thanks for documenting this and the solution!
