### ISSUE TITLE
OctoApp on Android crashes almost immediately

### ISSUE THREAD

**Issue by hyperair** [crysxd/OctoApp-Plugin#81]
I'm running OctoApp on an up to date Pixel 8 Pro, and recently it crashes almost immediately after connecting to my printer. I've tried clearing OctoApp's storage and cache in the Android app info settings page, but after setting it up to connect to my printer, it immediately crashed, and has been crashing since.

Some context -- I think this started happening after I disabled the OctoApp companion plugin in OctoPrint, while trying to debug print stalls coinciding with 100% CPU spikes in Octoprint. I have not tried reenabling it yet.

P.S. I know I'm supposed to submit a bug report through the app rather than directly in Github, but it won't stay open long enough to do that.

**Comment by crysxd** [comment]
I don't offer support via GitHub tickets, please send me an email to hello@octoapp.eu! :)

After a first look at my crash reports, I don't have anything that matches the description, so we'll need to come up with something to extract the crash logs from the device...
