### ISSUE TITLE
Moonraker Power Command in UI

### ISSUE THREAD

**Issue by J000K3R** [crysxd/OctoApp-Plugin#91]
**Is your feature request related to a problem? Please describe.**
Maybe it is possible to use the [power] config of Moonracker to switch on the printer via Homeassistant & Co.
I think this function would be useful for many who use the Octoapp with Klipper.

**Describe the solution you'd like**
The easiest way would be to have a button like when you use Octoprint to switch on the socket and other things.

**Additional context**
Here is the page for the configuration: https://github.com/Arksine/moonraker/blob/master/docs/configuration.md#power

Here is an example of my configuration:
```
[power Printer]
type: homeassistant
protocol: http
address: XXX
port: 8123
device: light.3d_drucker
token: XXX
domain: light
off_when_shutdown: True
restart_klipper_when_powered: True
```

When I go to the OctoApp myself, I only see the following screen:
![image](https://github.com/user-attachments/assets/01abb4b2-fa72-4799-b856-45afca9c093d)

**Comment by crysxd** [comment]
Moonraker power devices already show up in main menu > Moonraker > Power devices. Hold a device or a action button to pin it to the quick access. Send a bug report if this shouldn't work
