### ISSUE TITLE
Octoapp NEWB help!!!

### ISSUE THREAD

**Issue by ChunkiieCustomz** [crysxd/OctoApp-Plugin#94]
After searching I was unable to find what im looking for.. that being said I am VERY new to all of this so have some patients please .

Creality k1 max rooted, use mailsail.

I am trying to use octoapp with it  im getting python library files missing and then cant even verify its running after install..
![Screenshot 2024-10-06 224225](https://github.com/user-attachments/assets/20bb2784-ce67-4d8b-9e4c-2a07d48099cf)
![Screenshot 2024-10-06 221731](https://github.com/user-attachments/assets/632265d9-8914-45a5-a793-121e5667df96)

I have installed all the required things in the SSH. Octoapp plug in but then says missing file.. im sure i did something wrong just need a little help

**Comment by crysxd** [comment]
The root cause seems to be that `virtualenv` is missing. But you are also installing OctoEverywhere, not OctoApp.
Please see the manual: https://github.com/crysxd/OctoApp-Plugin/wiki/Installation-on-Creality

**Comment by ChunkiieCustomz** [comment]
Sent wrong screen shot but got to the point where says port is closed on octoapp "port 5000 is closed"

I did install ocotapp this isnt fixed 
![Screenshot 2024-10-07 084934](https://github.com/user-attachments/assets/c80d2a3b-50ee-4f68-8972-fab8bf0771da)

**Comment by crysxd** [comment]
You can run `rm -rf /usr/data/octoapp /usr/data/octoapp-env` to fully remove OctoApp and then retry the installation

If it keeps failing please send the full install log and not just a screenshot

**Comment by ChunkiieCustomz** [comment]
![Screenshot 2024-10-07 094141](https://github.com/user-attachments/assets/412a83da-0e5c-49e3-9698-33244fc40fb9)
same issue 

when trying to connect now it says ocotprint may be out of date...  im trying to connect through ios app ..

it ( the app) wont "find" my printer and when trying to type in address manually it says port closed or out of date app.  I really do appreciate the help I am not a programmer, I manage machines.... and obviously not well...

I did uninstall as requested then reinstalled.  the bus failure is all i see but im ignorant.

**Comment by crysxd** [comment]
This is a different error. 

I'm not sure what is wrong with your K1, but something is up. 

The error from the app also confuses me quite a bit, there is no OctoPrint involved. Please make sure to use the Mainsail or Fluidd URL when setting up the app. The plugin is not required to use the app.

Please long press the "Need help?" when you see the error in the app to send a bug report from the app, we go from there.
I can't offer support via GitHub (as the ticket description already says)

**Comment by ChunkiieCustomz** [comment]
HOLY CRAP.... SEE NEWB... I am sorry  url.. mainsail :4409 not :5000   thank you I am sorry I knew i was doing something wrong .
