### ISSUE TITLE
@Pause command notification

### ISSUE THREAD

**Issue by SDoehren** [crysxd/OctoApp-Plugin#96]
**Is your feature request related to a problem? Please describe.**
When printing a print that uses the @pause command, I have no way of know when that line is reached.

**Describe the solution you'd like**
A notification to be sent to my phone when the @pause command is reached in the gcode

**Comment by SDoehren** [comment]
Realised this does happen, I was just impatient.

**Comment by crysxd** [comment]
Yes, there is a delay in pause notifications. The reason is that some integrations purse the print temporarily and you don't want to get a notification e.g. every layer when a snapshot is taken.
