### ISSUE TITLE
Hide Certain G-Code Files

### ISSUE THREAD

**Issue by s00se** [crysxd/OctoApp-Plugin#97]
**Is your feature request related to a problem? Please describe.**

I usually always print the same file, but the quickview list of g-code files in the "Prepare" view contains other files, even though I haven't printed those other files in a long time. I'd like to keep the files around, but not show them in OctoApp unless I specifically want to browse or select them through the "Show files" dialog.

**Describe the solution you'd like**
It would be nice to be able to hide files, maybe ones that begin with a dot, or be able to select one file / pin a file to the Prepare view.

**Comment by crysxd** [comment]
That sounds more like a bug than a feature request. Quick print should only contain recently uploaded files, files you recently printed or the file that's currently selected. Printed files can also be hidden from the view settings in the file list.

Send a bug report from main menu > Settings > FAQ & Help > Send a bug report. Let's take a look :)

**Comment by s00se** [comment]
As you indicate, quick print does show recently uploaded files and files that have been recently printed. 

I am requesting a feature to disable showing specific or "stale" files so that they AREN'T shown. If I upload and print a file named XYZ1, and then upload and print a file name XYZ2, say 10 - 15 times, I would be nice to be able to clear X1 from the quick print list since I might not plan on printing it again, but want to keep the gcode stored in Octoprint.

**Comment by crysxd** [comment]
Thanks for the feedback:

To summarize, the "Quick view" shows files you don't want it to show. It shows the last printed and latest uploaded files as well as the one "selected" in the OctoPrint web UI.

I'm not a huge fan of adding extra settings here, but I can add a filter for files starting with `.` as you suggested. Does that sound like a good solution to you?

**Comment by s00se** [comment]
Yes, that is a suitable solution, thank you.

**Comment by crysxd** [comment]
Sorry for the delay.

The quick print shows now the following:

| Before | 2.3.1 | 
|--------|-------|
|   Currently selected file     |    Currently selected file  | 
|   Last uploaded     |  Laste uploaded, except if name starts with `.`     |  
|     Last prints   |     Last prints  |  

In total up to 5 items are picked.
This means if you just upload an file it's not shown but if you upload it and then select or print it it's shown even when it stats with `.`

**Comment by s00se** [comment]
Hm, I think filtering any file with a leading dot would make sense, even if it's already uploaded it should be hidden -- this would allow renaming existing files and having them hidden without having to re-upload them.

**Comment by crysxd** [comment]
2.2.33 is now on Google Play.

I now see your comment regarding the renaming...my thinking here was that if you actually print it it's important. My understanding was you upload files to archive them without printing

**Comment by crysxd** [comment]
2.2.35 will also hide files with `.` if they are already printed, but will still show it if it's currently "selected" / active.
